Repository DutchiePay/DutchiePay-Front, pull requests merged in 2024-10, with the labels that each got.

#21 Feat/withdraw api
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_mypage/Withdraw.jsx
Labels: 🛜API

#22 [feat] refresh token 존재 시, relogin API 호출
  dutchiepay/src/app/_components/_layout/Header.jsx
Labels: 🛜API, 🥳Feature

#23 [Design] input 자동완성 background color
  dutchiepay/src/styles/globals.css
Labels: 🎨HTML/CSS

#25 [design, fix] 배송지 관련 UI 및 마이페이지 API 호출 방식 변경
  dutchiepay/src/app/(modals)/change-number/page.jsx
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_layout/Sidebar.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx
  dutchiepay/src/app/layoutClient.js
  dutchiepay/src/redux/slice/addressSlice.js
  dutchiepay/src/redux/slice/userSlice.js
  dutchiepay/src/redux/store.js
  dutchiepay/src/styles/community.css
  dutchiepay/src/styles/globals.css
  dutchiepay/src/styles/mypage.css
Labels: 🐞BugFix, 🎨HTML/CSS, 🛜API

#26 [Feat] 소셜 회원가입/로그인/탈퇴 구현
  dutchiepay/public/image/profile.jpg
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_mypage/Withdraw.jsx
  dutchiepay/src/app/_components/_user/SocialLogin.jsx
  dutchiepay/src/app/_components/_user/SocialSignup.jsx
Labels: 🛜API, 🥳Feature

#27 [Fix] 휴대폰 번호 변경 시 저장 방식 변경 및 실시간 리렌더링
  dutchiepay/src/app/(modals)/change-number/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
Labels: 🐞BugFix, 🥳Feature

#34 [fix] 소셜 로그인/회원가입 성공 시 데이터 복호화 및 로그인 처리
  dutchiepay/src/app/_components/_user/SocialLogin.jsx
  dutchiepay/src/app/_components/_user/SocialSignup.jsx
Labels: 🐞BugFix, 🥳Feature

#29 [feat] 회원 비밀번호 재설정 시 현재 비밀번호 추가, 이메일,닉네임 중복검사, 전화번호 필수로 입력하게 구현
  dutchiepay/src/app/_components/_user/EmailInput.jsx
  dutchiepay/src/app/_components/_user/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/NicknameInput.jsx
  dutchiepay/src/app/_components/_user/PasswordInput.jsx
  dutchiepay/src/app/_components/_user/PhoneAuth.jsx
  dutchiepay/src/app/_components/_user/ResetSubmit.jsx
  dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
Labels: 🥳Feature

#33 [Fix] 배송지 호출 관련 오류 해결 및 추가/수정/삭제 API 처리
  dutchiepay/next.config.mjs
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx
  dutchiepay/src/redux/slice/addressSlice.js
  dutchiepay/src/redux/slice/loginSlice.js
Labels: 🐞BugFix, 🛜API, 🥳Feature

#36 [Fix] 배송지 추가/수정/삭제 시 API 재호출 및 수정 페이지 데이터 소멸 오류 해결
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/_components/_commerce/Orderer.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx
  dutchiepay/src/app/_components/_user/EmailInput.jsx
  dutchiepay/src/app/_components/_user/SocialLogin.jsx
Labels: 🐞BugFix, 🛜API

#37 [fix] 마이페이지에서 로그아웃 시 addresses가 null이 되지 않는 오류 수정
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx
Labels: 🐞BugFix

#38 [chore] image domains deprecated 관련 수정
  dutchiepay/next.config.mjs
Labels: ⚙️Setting

#39 [fix] 소셜 로그인 복호화 오류 해결
  dutchiepay/src/app/_components/_user/SocialLogin.jsx
  dutchiepay/src/app/_components/_user/SocialSignup.jsx
Labels: 🐞BugFix

#44 [Fix] user API 에러 처리
  dutchiepay/src/app/(routes)/extra-info/page.jsx
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_user/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/ResetSubmit.jsx
  dutchiepay/src/app/layoutClient.js
Labels: 🐞BugFix, 🛜API

#45 [feat] 기본 배송지를 일반 배송지로 변경 시 처리 및 기본 배송지 변경 버튼 추가
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx
  dutchiepay/src/app/layoutClient.js
Labels: 🛜API, 🥳Feature

#46 [Design] mypage UI 수정
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/(routes)/mypage/like/page.jsx
  dutchiepay/src/app/(routes)/mypage/myask/page.jsx
  dutchiepay/src/app/(routes)/mypage/mycoupon/page.jsx
  dutchiepay/src/app/(routes)/mypage/myorder/page.jsx
  dutchiepay/src/app/(routes)/mypage/mypost/page.jsx
  dutchiepay/src/app/(routes)/mypage/myreview/page.jsx
  dutchiepay/src/app/_components/_layout/Sidebar.jsx
Labels: 🎨HTML/CSS

#48 [Fix] mypage 관련 오류 수정
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
Labels: 🐞BugFix, 🎨HTML/CSS, 🛜API, 🥳Feature

#49 [Fix] 테스트/회의에서 수정된 사항을 일부 반영
  dutchiepay/src/app/(modals)/coupon/page.jsx
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/(routes)/mypage/like/page.jsx
  dutchiepay/src/app/(routes)/mypage/mycoupon/page.jsx
  dutchiepay/src/app/(routes)/order/page.jsx
  dutchiepay/src/app/_components/_commerce/AvailableCoupons.jsx
  dutchiepay/src/app/_components/_commerce/CouponChoice.jsx
  dutchiepay/src/app/_components/_commerce/Payment.jsx
  dutchiepay/src/app/_components/_commerce/PaymentChoice.jsx
  dutchiepay/src/app/_components/_layout/Sidebar.jsx
  dutchiepay/src/app/_components/_mypage/Coupon_List.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx
  dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx
  dutchiepay/src/app/_components/_user/EmailInput.jsx
  dutchiepay/src/app/_components/_user/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/ResetSubmit.jsx
  dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
  dutchiepay/src/styles/mypage.css
Labels: 🐞BugFix, 🎨HTML/CSS, 🛜API

#50 [Refactor] 이미지 버킷 업로드 함수 분리
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/GetImage.jsx
Labels: ⚒️Refactor

#51 [fix] 이벤트 관련 페이지/컴포넌트/이미지 삭제
  dutchiepay/public/image/event.jpg
  dutchiepay/public/image/event.png
  dutchiepay/public/image/event/eventDetail1.gif
  dutchiepay/public/image/event/eventDetail1_2.jpg
  dutchiepay/public/image/event/eventDetail2.gif
  dutchiepay/public/image/event/eventDetail2_1.jpg
  dutchiepay/public/image/event/eventDetail3.jpg
  dutchiepay/public/image/event2.jpg
  dutchiepay/public/image/event3.jpg
  dutchiepay/src/app/(routes)/event/[id]/page.jsx
  dutchiepay/src/app/(routes)/event/page.jsx
  dutchiepay/src/app/_components/EventDetail.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
Labels: ⚙️Setting

#52 [feat] 휴대폰 번호 입력 시 하이픈(-) 무시
  dutchiepay/src/app/(modals)/change-number/page.jsx
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/_components/_commerce/Orderer.jsx
  dutchiepay/src/app/_components/_user/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/PhoneAuth.jsx
  dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
Labels: 🥳Feature

#55 [refactor] 로그인 컴포넌트 분리
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/(routes)/signup/page.jsx
  dutchiepay/src/app/_components/_user/SocialSignup.jsx
  dutchiepay/src/app/_components/_user/_login/LastLogin.jsx
  dutchiepay/src/app/_components/_user/_login/LoginButton.jsx
  dutchiepay/src/app/_components/_user/_login/LoginInput.jsx
  dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx
  dutchiepay/src/app/_components/_user/_login/RememberMe.jsx
  dutchiepay/src/app/_components/_user/_login/SocialButton.jsx
  dutchiepay/src/app/_components/_user/_login/SocialLogin.jsx
Labels: ⚒️Refactor

#60 [fix] 변경 사항 수정 누락 및 불필요한 변수 생성 코드 삭제
  dutchiepay/src/app/(routes)/extra-info/page.jsx
  dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
Labels: 🐞BugFix

#58 [refactor] 계정 찾기 컴포넌트 분리
  dutchiepay/src/app/(routes)/find/page.jsx
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/(routes)/reset/page.jsx
  dutchiepay/src/app/(routes)/signup/page.jsx
  dutchiepay/src/app/_components/_user/EmailInput.jsx
  dutchiepay/src/app/_components/_user/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/Logo.jsx
  dutchiepay/src/app/_components/_user/_find/FindDescription.jsx
  dutchiepay/src/app/_components/_user/_find/FindFilter.jsx
  dutchiepay/src/app/_components/_user/_find/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/_find/FindSuccess.jsx
  dutchiepay/src/styles/user.css
Labels: ⚒️Refactor

#59 [refactor] 비밀번호 input 컴포넌트 분리
  dutchiepay/src/app/(routes)/reset/page.jsx
  dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
  dutchiepay/src/app/_components/_user/PasswordInput.jsx
  dutchiepay/src/app/_components/_user/ResetSubmit.jsx
  dutchiepay/src/app/_components/_user/_find/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/_input/AddressInput.jsx
  dutchiepay/src/app/_components/_user/_input/ConfirmPassword.jsx
  dutchiepay/src/app/_components/_user/_input/CurrentPassword.jsx
  dutchiepay/src/app/_components/_user/_input/EmailInput.jsx
  dutchiepay/src/app/_components/_user/_input/NewPassword.jsx
  dutchiepay/src/app/_components/_user/_input/NicknameInput.jsx
  dutchiepay/src/app/_components/_user/_input/PasswordInput.jsx
  dutchiepay/src/app/_components/_user/_signup/SignUpSubmit.jsx
Labels: ⚒️Refactor

#62 [Refactor] 회원정보 수정 컴포넌트 분리
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_layout/Sidebar.jsx
  dutchiepay/src/app/_components/_mypage/AccountInfo.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ModifyLocation.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ModifyNickname.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ModifyNumber.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ModifyProfileImg.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ProfileImgButton.jsx
Labels: ⚒️Refactor

#64 [Test] header, sidebar, emailInput, passwordInput story
  dutchiepay/.storybook/preview.js
  dutchiepay/src/stories/Button.jsx
  dutchiepay/src/stories/Button.stories.js
  dutchiepay/src/stories/EmailInput.stories.js
  dutchiepay/src/stories/Header.jsx
  dutchiepay/src/stories/Header.stories.js
  dutchiepay/src/stories/Page.jsx
  dutchiepay/src/stories/Page.stories.js
  dutchiepay/src/stories/PasswordInput.stories.js
  dutchiepay/src/stories/Sidebar.stories.js
  dutchiepay/src/stories/button.css
  dutchiepay/src/stories/header.css
  dutchiepay/src/stories/page.css
Labels: ✅Test

#65 [fix] sidebar가 footer를 가리는 현상 수정
  dutchiepay/src/app/_components/_layout/Footer.jsx
  dutchiepay/src/app/_components/_layout/Sidebar.jsx
Labels: 🐞BugFix

#66 [Fix] validation 오류 수정 및 user 관련 페이지 logo warning 해결
  dutchiepay/src/app/_components/_user/Logo.jsx
  dutchiepay/src/app/_components/_user/_input/ConfirmPassword.jsx
  dutchiepay/src/app/_components/_user/_input/EmailInput.jsx
  dutchiepay/src/app/_components/_user/_input/NicknameInput.jsx
  dutchiepay/src/app/_components/_user/_input/PasswordInput.jsx
  dutchiepay/src/app/_components/_user/_signup/SignUpSubmit.jsx
Labels: 🐞BugFix

#71 Feat/product addition
  dutchiepay/src/app/(routes)/addition/page.jsx
Labels: 🥳Feature

#70 [Test] 로그인 스토리 추가, 비밀번호 스토리 오류 해결
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/_components/_user/_input/NicknameInput.jsx
  dutchiepay/src/app/_components/_user/_login/LoginInput.jsx
  dutchiepay/src/stories/EmailInput.stories.js
  dutchiepay/src/stories/Login.stories.js
  dutchiepay/src/stories/NicknameInput.stories.js
  dutchiepay/src/stories/PasswordInput.stories.js
  dutchiepay/src/stories/PhoneInput.stories.js
  dutchiepay/src/styles/user.css
Labels: ✅Test

#75 [Feat] 상품 리스트 무한스크롤 및 카테고리/필터값에 따른 상품 불러오기
  dutchiepay/package-lock.json
  dutchiepay/package.json
  dutchiepay/src/app/(routes)/commerce/page.jsx
  dutchiepay/src/app/_components/_commerce/Product_List.jsx
  dutchiepay/src/app/_components/_commerce/_product/ProductCategory.jsx
  dutchiepay/src/app/_components/_commerce/_product/ProductFilter.jsx
  dutchiepay/src/app/_components/_commerce/_product/ProductItem.jsx
  dutchiepay/src/app/_components/_commerce/_product/ProductLike.jsx
  dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
  dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx
  dutchiepay/src/app/_util/constants.js
  dutchiepay/src/styles/commerce.css
  dutchiepay/src/styles/globals.css
Labels: 🛜API, 🥳Feature

#77 [refactor] util 함수 폴더 위치 변경, useOauthLogin hook 구현
  dutchiepay/src/app/(routes)/addition/page.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ModifyLocation.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ProfileImgButton.jsx
  dutchiepay/src/app/_components/_user/_input/AddressInput.jsx
  dutchiepay/src/app/_components/_user/_login/SocialLogin.jsx
  dutchiepay/src/app/_components/_user/_signup/SocialSignup.jsx
  dutchiepay/src/app/_util/GetImage.js
  dutchiepay/src/app/_util/GetLocation.js
  dutchiepay/src/app/_util/RemainingTime.js
  dutchiepay/src/app/hooks/useOauthLogin.jsx
  dutchiepay/src/app/layout.jsx
  dutchiepay/src/app/layoutClient.jsx
  dutchiepay/src/app/page.jsx
Labels: ⚒️Refactor, 🥳Feature

#79 [Feat] 상품 상세 페이지 구현
  dutchiepay/src/app/(routes)/addition/page.jsx
  dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
  dutchiepay/src/app/(routes)/commerce/detail/page.jsx
  dutchiepay/src/app/_components/_commerce/ProductInfo.jsx
  dutchiepay/src/app/_components/_commerce/_product/ProductItem.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/Company.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/DeliveryAndLikeInfo.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/OrderButton.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/ProductContent.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/ProductDetailTab.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/ProductHeader.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/ProductInfo.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/ProductStats.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/ProductTitle.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/Quantity.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/RemainingTime.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ModifyLocation.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ProfileImgButton.jsx
  dutchiepay/src/app/_components/_user/_input/AddressInput.jsx
  dutchiepay/src/app/_util/getCategoryNames.js
  dutchiepay/src/app/_util/getRemainingTime.js
Labels: 🛜API, ⚒️Refactor, 🥳Feature

#83 [fix] 추가 정보 입력 후 isCertified 변경되지 않는 오류 수정
  dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
  dutchiepay/src/redux/slice/loginSlice.js
Labels: 🐞BugFix

#84 [rename] 함수 이름 변경
  dutchiepay/src/app/_util/getImage.js
  dutchiepay/src/app/_util/getLocation.js
Labels: 🐞BugFix

#81 [init] eslint 설정
  dutchiepay/.eslintrc.json
  dutchiepay/package-lock.json
  dutchiepay/package.json
Labels: ⚙️Setting

#86 [fix] eslint 에러 해결
  dutchiepay/.eslintrc.json
  dutchiepay/src/app/(modals)/auth-phone/page.jsx
  dutchiepay/src/app/(modals)/change-number/page.jsx
  dutchiepay/src/app/(modals)/delivery-address/page.jsx
  dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
  dutchiepay/src/app/(routes)/extra-info/page.jsx
  dutchiepay/src/app/(routes)/introduction/page.jsx
  dutchiepay/src/app/(routes)/location/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/(routes)/reset/page.jsx
  dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/Quantity.jsx
  dutchiepay/src/app/_components/_commerce/_productDetail/RemainingTime.jsx
  dutchiepay/src/app/_components/_layout/Sidebar.jsx
  dutchiepay/src/app/_components/_mypage/_delivery/AddressAddition.jsx
  dutchiepay/src/app/_components/_mypage/_delivery/DeliveryAddress.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ModifyNumber.jsx
  dutchiepay/src/app/_components/_mypage/_modify/ProfileImgButton.jsx
  dutchiepay/src/app/_components/_rating/Rating.jsx
  dutchiepay/src/app/_components/_user/ResetSubmit.jsx
  dutchiepay/src/app/_components/_user/_find/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/_input/AddressInput.jsx
  dutchiepay/src/app/_components/_user/_input/NicknameInput.jsx
  dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx
  dutchiepay/src/app/_components/_user/_phone/AuthCode.jsx
  dutchiepay/src/app/_components/_user/_phone/PhoneInput.jsx
  dutchiepay/src/app/_util/getLocation.js
  dutchiepay/src/app/_util/getStarRates.js
Labels: 🐞BugFix
