Repository DutchiePay/DutchiePay-Front, pull requests merged in 2024-09, with the labels that each got.

#1 Design/UI changes (로딩스피너, 상품/게시글 UI, 필터, Image 최적화 등 디자인 수 )
  dutchiepay/public/image/fullheart.svg
  dutchiepay/public/image/heart.svg
  dutchiepay/src/app/(routes)/commerce/page.jsx
  dutchiepay/src/app/(routes)/community/page.jsx
  dutchiepay/src/app/(routes)/reset/page.jsx
  dutchiepay/src/app/(routes)/search/[section]/page.jsx
  dutchiepay/src/app/_components/Post.jsx
  dutchiepay/src/app/_components/Product.jsx
  dutchiepay/src/app/_components/_commerce/Product_List.jsx
  dutchiepay/src/app/_components/_community/Post_Community.jsx
  dutchiepay/src/app/_components/_community/Post_Mart.jsx
  dutchiepay/src/app/_components/_community/Post_Used.jsx
  dutchiepay/src/app/_components/_landing/MainCarousel.jsx
  dutchiepay/src/app/_components/_landing/Product_Hot.jsx
  dutchiepay/src/app/_components/_landing/Product_Main.jsx
  dutchiepay/src/app/layoutClient.js
  dutchiepay/src/app/loading.jsx
  dutchiepay/src/styles/commerce.css
  dutchiepay/src/styles/globals.css
Labels: 🎨HTML/CSS

#2 [feat] 회원가입/로그인 API 호출 / [refactor] 위치정보 컴포넌트 분리
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/(routes)/signup/page.jsx
  dutchiepay/src/app/_components/_user/GetLocation.jsx
Labels: 🛜API, ⚒️Refactor, 🥳Feature

#3 [chore] storybook 설치 및 Storybook/PostCSS 설정
  dutchiepay/.eslintrc.json
  dutchiepay/.gitignore
  dutchiepay/.storybook/main.js
  dutchiepay/.storybook/preview.js
  dutchiepay/package-lock.json
  dutchiepay/package.json
  dutchiepay/postcss.config.mjs
  dutchiepay/src/stories/Button.jsx
  dutchiepay/src/stories/Button.stories.js
  dutchiepay/src/stories/Configure.mdx
  dutchiepay/src/stories/Header.jsx
  dutchiepay/src/stories/Header.stories.js
  dutchiepay/src/stories/Page.jsx
  dutchiepay/src/stories/Page.stories.js
  dutchiepay/src/stories/assets/accessibility.png
  dutchiepay/src/stories/assets/accessibility.svg
  dutchiepay/src/stories/assets/addon-library.png
  dutchiepay/src/stories/assets/assets.png
  dutchiepay/src/stories/assets/avif-test-image.avif
  dutchiepay/src/stories/assets/context.png
  dutchiepay/src/stories/assets/discord.svg
  dutchiepay/src/stories/assets/docs.png
  dutchiepay/src/stories/assets/figma-plugin.png
  dutchiepay/src/stories/assets/github.svg
  dutchiepay/src/stories/assets/share.png
  dutchiepay/src/stories/assets/styling.png
  dutchiepay/src/stories/assets/testing.png
  dutchiepay/src/stories/assets/theming.png
  dutchiepay/src/stories/assets/tutorials.svg
  dutchiepay/src/stories/assets/youtube.svg
  dutchiepay/src/stories/button.css
  dutchiepay/src/stories/header.css
  dutchiepay/src/stories/page.css
Labels: ⚙️Setting, ✅Test

#5 [fix] 정적 배포를 위한 middleware 삭제, next.config.js에서 리다이렉션 설정
  dutchiepay/next.config.mjs
  dutchiepay/src/middleware.js
Labels: 🐞BugFix, 🌏Deploy

#6 [feat] 회원가입 유효성 강화, 휴대폰 인증 컴포넌트 분리, GeoLocation 불필요한 코드 제거
  dutchiepay/src/app/(routes)/signup/page.jsx
  dutchiepay/src/app/_components/_user/GetLocation.jsx
  dutchiepay/src/app/_components/_user/PhoneAuth.jsx
Labels: ⚒️Refactor, 🥳Feature

#7 [fix] order 페이지 hydration 오류 해결 및 refactor
  dutchiepay/public/image/kakaoPayment.png
  dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
  dutchiepay/src/app/(routes)/order/page.jsx
  dutchiepay/src/app/_components/_commerce/CouponChoice.jsx
  dutchiepay/src/app/_components/_commerce/OrderInfo.jsx
  dutchiepay/src/app/_components/_commerce/Orderer.jsx
  dutchiepay/src/app/_components/_commerce/Payment.jsx
  dutchiepay/src/app/_components/_commerce/PaymentChoice.jsx
  dutchiepay/src/app/_components/_commerce/ProductInfo.jsx
  dutchiepay/src/styles/commerce.css
Labels: 🐞BugFix, 🎨HTML/CSS, ⚒️Refactor, 👨‍👩‍👧‍👦Acccessibility

#8 [fix] 수동 리디렉션 설정으로 변경
  dutchiepay/next.config.mjs
  dutchiepay/src/app/(routes)/mypage/page.jsx
Labels: 🐞BugFix

#9 [fix] 동적 라우팅 페이지 쿼리로 변경
  dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
  dutchiepay/src/app/(routes)/commerce/detail/page.jsx
  dutchiepay/src/app/(routes)/community/detail/page.jsx
  dutchiepay/src/app/(routes)/mart/detail/page.jsx
  dutchiepay/src/app/(routes)/used/detail/page.jsx
  dutchiepay/src/app/_components/Post.jsx
  dutchiepay/src/app/_components/Product.jsx
  dutchiepay/src/app/_components/_commerce/Product_List.jsx
  dutchiepay/src/app/_components/_community/Post_Community.jsx
  dutchiepay/src/app/_components/_community/Post_Complete.jsx
  dutchiepay/src/app/_components/_community/Post_Hot.jsx
  dutchiepay/src/app/_components/_community/Post_Mart.jsx
  dutchiepay/src/app/_components/_community/Post_Similar.jsx
  dutchiepay/src/app/_components/_community/Post_Used.jsx
  dutchiepay/src/app/_components/_landing/Product_Hot.jsx
  dutchiepay/src/app/_components/_landing/Product_Main.jsx
  dutchiepay/src/app/_components/_mypage/MyAsk.jsx
  dutchiepay/src/app/_components/_mypage/MyReview.jsx
  dutchiepay/src/app/_components/_mypage/Order.jsx
Labels: 🐞BugFix

#10 [feat] 회원 정보 수정 변경 취소 시 기존 유저 정보로 변경 완료 시 변경된 유저 정보로 바뀌게 구현
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
Labels: 👨‍👩‍👧‍👦Acccessibility, 🥳Feature

#11 [Refactor] 회원가입 컴포넌트 분리 및 리팩토링
  dutchiepay/src/app/(routes)/find/page.jsx
  dutchiepay/src/app/(routes)/signup/page.jsx
  dutchiepay/src/app/_components/_user/AddressInput.jsx
  dutchiepay/src/app/_components/_user/EmailInput.jsx
  dutchiepay/src/app/_components/_user/NameInput.jsx
  dutchiepay/src/app/_components/_user/NicknameInput.jsx
  dutchiepay/src/app/_components/_user/PasswordInput.jsx
  dutchiepay/src/app/_components/_user/PhoneAuth.jsx
  dutchiepay/src/app/_components/_user/Policy.jsx
  dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
  dutchiepay/src/app/_components/_user/SocialSignup.jsx
Labels: 🛜API, ⚒️Refactor

#12 [Design] 회원정보 UI 일부 추가
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
Labels: 🎨HTML/CSS

#13 [feat] 로그인 API, 로그인 정보 redux 및 쿠키 저장
  dutchiepay/package-lock.json
  dutchiepay/package.json
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/_components/_layout/Header.jsx
  dutchiepay/src/app/_components/_layout/Sidebar.jsx
  dutchiepay/src/app/layoutClient.js
  dutchiepay/src/redux/slice/loginSlice.js
  dutchiepay/src/redux/store.js
Labels: 🛜API, 🥳Feature

#14 [Refactor/Feat] 계정 찾기, 재설정 페이지 리팩토링 및 API 추가
  dutchiepay/src/app/(routes)/find/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/(routes)/reset/page.jsx
  dutchiepay/src/app/(routes)/signup/page.jsx
  dutchiepay/src/app/_components/_user/AddressInput.jsx
  dutchiepay/src/app/_components/_user/EmailInput.jsx
  dutchiepay/src/app/_components/_user/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/FindSuccess.jsx
  dutchiepay/src/app/_components/_user/PasswordInput.jsx
  dutchiepay/src/app/_components/_user/PhoneAuth.jsx
  dutchiepay/src/app/_components/_user/Policy.jsx
  dutchiepay/src/app/_components/_user/ResetSubmit.jsx
  dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
  dutchiepay/src/app/_components/_user/SocialSignup.jsx
Labels: 🛜API, ⚒️Refactor, 🥳Feature

#15 [feat] 파일 불러오기 후 유효성 검사 통과된 이미지만 S3 업로드 구현
  dutchiepay/package-lock.json
  dutchiepay/package.json
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
Labels: 🛜API, 🥳Feature

#16 [feat, fix] 최근 로그인 방식 표시 및 컴포넌트 분리
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/_components/_user/LastLogin.jsx
  dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
  dutchiepay/src/app/_components/_user/SocialLogin.jsx
  dutchiepay/src/redux/slice/loginSlice.js
Labels: ⚒️Refactor, 🥳Feature

#17 [Feat] 휴대폰 번호 변경
  dutchiepay/src/app/(modals)/change-number/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_user/PhoneAuth.jsx
  dutchiepay/src/app/layoutClient.js
Labels: 🎨HTML/CSS, 🛜API, 🥳Feature

#18 [Fix] 휴대폰 인증번호 확인 추가 및 회원가입 성함 항목 삭제
  dutchiepay/src/app/(modals)/change-number/page.jsx
  dutchiepay/src/app/(routes)/login/page.jsx
  dutchiepay/src/app/(routes)/mypage/info/page.jsx
  dutchiepay/src/app/_components/_user/EmailInput.jsx
  dutchiepay/src/app/_components/_user/FindSubmit.jsx
  dutchiepay/src/app/_components/_user/NameInput.jsx
  dutchiepay/src/app/_components/_user/PhoneAuth.jsx
  dutchiepay/src/app/_components/_user/ResetSubmit.jsx
  dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
Labels: 🛜API, 👨‍👩‍👧‍👦Acccessibility, 🥳Feature

#19 [design] 로딩 스피너 css 변경
  dutchiepay/src/styles/globals.css
Labels: 🎨HTML/CSS
